language: php

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - composer info -i

script:
  - vendor/bin/phpspec run
